import os
from github import Github, GithubException
from langchain_core.tools import tool
from dotenv import load_dotenv

load_dotenv()


def _get_github_client():
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN not found in .env file")
    return Github(token)


@tool
def fetch_pr_details(repo_name: str, pr_number: int) -> str:
    """
    Fetches details of a GitHub Pull Request including title,
    description, changed files and the actual code diff.
    
    Args:
        repo_name: GitHub repo in format 'owner/repo' e.g. 'facebook/react'
        pr_number: The PR number to fetch e.g. 42
    """
    try:
        g = _get_github_client()
        repo = g.get_repo(repo_name)
        pr = repo.get_pull(pr_number)

        details = []
        details.append(f"## PR #{pr_number}: {pr.title}")
        details.append(f"**Author:** {pr.user.login}")
        details.append(f"**Branch:** {pr.head.ref} → {pr.base.ref}")

        if pr.body:
            details.append(f"\n**Description:**\n{pr.body}")
        else:
            details.append("\n**Description:** (none provided)")

        details.append(f"\n**Changes:** +{pr.additions} additions, -{pr.deletions} deletions across {pr.changed_files} files")
        details.append("\n---\n## Changed Files & Diffs\n")

        for file in pr.get_files():
            details.append(f"\n### `{file.filename}`")
            details.append(f"Status: {file.status} | +{file.additions} -{file.deletions}")

            if file.patch:
                patch = file.patch[:3000]
                if len(file.patch) > 3000:
                    patch += "\n... (diff truncated)"
                details.append(f"```diff\n{patch}\n```")
            else:
                details.append("*(Binary file or no diff available)*")

        return "\n".join(details)

    except GithubException as e:
        return f"GitHub API error: {e.status} - {e.data.get('message', str(e))}"
    except Exception as e:
        return f"Error fetching PR: {str(e)}"


@tool
def post_review_comment(repo_name: str, pr_number: int, review_body: str) -> str:
    """
    Posts a review comment on a GitHub Pull Request.
    Use this after analyzing the code and writing the review.
    
    Args:
        repo_name: GitHub repo in format 'owner/repo'
        pr_number: The PR number to comment on
        review_body: The full review text in Markdown format
    """
    try:
        g = _get_github_client()
        repo = g.get_repo(repo_name)
        pr = repo.get_pull(pr_number)

        formatted_body = (
            "## AI Code Review\n\n"
            "> *Generated by AI Code Review Agent*\n\n"
            "---\n\n"
            f"{review_body}"
        )

        review = pr.create_review(body=formatted_body, event="COMMENT")
        return f"Review posted! View at: {pr.html_url}#pullrequestreview-{review.id}"

    except GithubException as e:
        return f"GitHub API error: {e.status} - {e.data.get('message', str(e))}"
    except Exception as e:
        return f"Error posting review: {str(e)}"